domain: maas.io

image: prod-comms.docker-registry.canonical.com/maas.io

env:
  - name: SENTRY_DSN
    value: https://66c89fd7773e4b408d3e25867d6899e9@sentry.is.canonical.com//6

  - name: SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

extraHosts:
  - domain: docs.maas.io
  - domain: maas.ubuntu.com
  - domain: maas.ubunut.com

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host = 'maas.ubuntu.com' ) {
      rewrite ^ https://maas.io/legacy$request_uri? permanent;
    }
    if ($host = 'maas.ubunut.com' ) {
      rewrite ^ https://maas.io/legacy$request_uri? permanent;
    }
    if ($host = 'docs.maas.io' ) {
      rewrite ^ https://maas.io/docs$request_uri? permanent;
    }
    if ($host != 'maas.io' ) {
      rewrite ^ https://maas.io$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    if ($host = 'maas.staging.ubuntu.com' ) {
      rewrite ^ https://staging.maas.io/legacy$request_uri? permanent;
    }
    if ($host = 'maas.staging.ubunut.com' ) {
      rewrite ^ https://staging.maas.io/legacy$request_uri? permanent;
    }
    if ($host = 'docs.staging.maas.io' ) {
      rewrite ^ https://staging.maas.io/docs$request_uri? permanent;
    }
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
